const MyDefaultTheme = {
	dark: false,
	colors: {
		background: "#f7f7f7",
		background2: "#eff3f4",
		border: "#858585",
		button: "#3454fc",
		card: "#ffffff",
		notification: "#ff3b30",
		primary: "#007aff",
		secondary: "#E7EAF6",
		text: "#393E46",
		textInput: "#ffffff",
		surface: "black",
		accent: "black",
		icon: "black",
		onSurface: "black",
		disabled: "black",
		placeholder: "black",
		backdrop: "black",
	},
};

const MyDarkTheme = {
	dark: true,
	colors: {
		background: "#000000",
		background2: "#000000",
		border: "#ffffff",
		button: "#3454fc",
		card: "#0a0a0a",
		notification: "#ff453a",
		primary: "#0a84ff",
		secondary: "#242424",
		text: "white",
		textInput: "#0a0a0a",
		surface: "#454f57",
		accent: "#e5e5e7",
		icon: "white",
		onSurface: "black",
		disabled: "black",
		placeholder: "white",
		backdrop: "black",
	},
};
export { MyDarkTheme, MyDefaultTheme };
